### ISSUE TITLE
memory leak while building roar_graph on dataset text-to-image10M

### ISSUE THREAD

**Issue by mqqqqj** [matchyc/RoarGraph#3]
## memory leak while building roar_graph on dataset text-to-image10M

I ran into a memory leak when I did 'bash run_roargraph_test.sh'. Is it the code for building the index that caused this problem or is there another reason?

### environment
- OS: centos7
- gcc/g++ version:13.2
- boost version: 1.67

### to reproduce
- compute groundtruth using utils provided by DiskANN
- bash run_roargraph_test.sh
- run 'htop' to observe memory usage

![memory leak](https://github.com/user-attachments/assets/5e06cb86-f0e7-40fd-b112-7d4299b51b05)

**Comment by matchyc** [comment]
you can try to reduce the batch size in the compute_ground truth cpp file to fit your machine capacity.

**Comment by matchyc** [comment]
I'm also not sure whether the program provided by diskann works as expected on centos since it was developed on ubuntu with mkl dependency.

**Comment by mqqqqj** [comment]
@matchyc Thanks for your answer. Maybe I didn't explain it clearly. Everything works fine when I calculate the gt. Memory leak happened during executing **./tests/test_build_roargraph xxxxx(as written in your run_roargraph_test.sh)**.

**Comment by matchyc** [comment]
That's unreasonable, less memory is needed during graph build. Any log?

**Comment by matchyc** [comment]
Please also check if the file exists.

**Comment by mqqqqj** [comment]
> Please also check if the file exists.
Thank you for your response and for bringing this to my attention! I realized that I did indeed save the ground truth in an incorrect directory, which resulted in the inability to properly read learn_base_nn. Consequently, this has led to a memory leak issue. This issue is solved.

**Comment by matchyc** [comment]
@mqqqqj You can contribute a pull request of adding a "file existence check" when loading this file.
